const allTypes = [
    {code: '10', type: 'D'},
    {code: '12', type: 'DI'},
    {code: '13', type: 'DS'},
    {code: '14', type: 'DC'},
    {code: '16', type: 'Di'},
    {code: '17', type: 'Ds'},
    {code: '18', type: 'Dc'},
    {code: '20', type: 'I'},
    {code: '23', type: 'IS'},
    {code: '24', type: 'IC'},
    {code: '25', type: 'Id'},
    {code: '27', type: 'Is'},
    {code: '28', type: 'Ic'},
    {code: '30', type: 'S'},
    {code: '34', type: 'SC'},
    {code: '35', type: 'Sd'},
    {code: '36', type: 'Si'},
    {code: '38', type: 'Sc'},
    {code: '40', type: 'C'},
    {code: '45', type: 'Cd'},
    {code: '46', type: 'Ci'},
    {code: '47', type: 'Cs'},
    {code: '50', type: 'd'},
    {code: '56', type: 'di'},
    {code: '57', type: 'ds'},
    {code: '58', type: 'dc'},
    {code: '60', type: 'i'},
    {code: '67', type: 'is'},
    {code: '68', type: 'ic'},
    {code: '70', type: 's'},
    {code: '78', type: 'sc'},
    {code: '80', type: 'c'},
    {code: '99', type: 'o'},
]

export default allTypes